### ISSUE TITLE
3.9.0: documentation build fails with `cannot import name 'set_module' from 'numpy.core.overrides'` error message

### ISSUE THREAD

**Issue by kloczek** [matplotlib/mpl-sphinx-theme#89]
Looks like documentation build fails
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.3.7

Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/usr/lib64/python3.10/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/usr/lib64/python3.10/site-packages/numpy/core/__init__.py", line 74, in <module>
    from . import numeric
  File "/usr/lib64/python3.10/site-packages/numpy/core/numeric.py", line 27, in <module>
    from .overrides import set_array_function_like_doc, set_module
ImportError: cannot import name 'set_module' from 'numpy.core.overrides' (/usr/lib64/python3.10/site-packages/numpy/core/overrides.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/config.py", line 509, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/mpl-sphinx-theme-3.9.0/docs/conf.py", line 4, in <module>
    import matplotlib  # noqa: F401
  File "/usr/lib64/python3.10/site-packages/matplotlib/__init__.py", line 156, in <module>
    import numpy
  File "/usr/lib64/python3.10/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 211, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.10/site-packages/sphinx/config.py", line 309, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.10/site-packages/sphinx/config.py", line 522, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/usr/lib64/python3.10/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/usr/lib64/python3.10/site-packages/numpy/core/__init__.py", line 74, in <module>
    from . import numeric
  File "/usr/lib64/python3.10/site-packages/numpy/core/numeric.py", line 27, in <module>
    from .overrides import set_array_function_like_doc, set_module
ImportError: cannot import name 'set_module' from 'numpy.core.overrides' (/usr/lib64/python3.10/site-packages/numpy/core/overrides.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/config.py", line 509, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/mpl-sphinx-theme-3.9.0/docs/conf.py", line 4, in <module>
    import matplotlib  # noqa: F401
  File "/usr/lib64/python3.10/site-packages/matplotlib/__init__.py", line 156, in <module>
    import numpy
  File "/usr/lib64/python3.10/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/usr/lib64/python3.10/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/usr/lib64/python3.10/site-packages/numpy/core/__init__.py", line 74, in <module>
    from . import numeric
  File "/usr/lib64/python3.10/site-packages/numpy/core/numeric.py", line 27, in <module>
    from .overrides import set_array_function_like_doc, set_module
ImportError: cannot import name 'set_module' from 'numpy.core.overrides' (/usr/lib64/python3.10/site-packages/numpy/core/overrides.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/config.py", line 509, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/mpl-sphinx-theme-3.9.0/docs/conf.py", line 4, in <module>
    import matplotlib  # noqa: F401
  File "/usr/lib64/python3.10/site-packages/matplotlib/__init__.py", line 156, in <module>
    import numpy
  File "/usr/lib64/python3.10/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

````
List of installed modules in build env
```console
Package                       Version
----------------------------- -----------
alabaster                     0.7.16
Babel                         2.15.0
build                         1.2.1
charset-normalizer            3.3.2
contourpy                     1.2.1
cycler                        0.12.1
defusedxml                    0.7.1
docutils                      0.20.1
exceptiongroup                1.1.3
fonttools                     4.51.0
idna                          3.7
imagesize                     1.4.1
importlib_metadata            7.1.0
iniconfig                     2.0.0
installer                     0.7.0
Jinja2                        3.1.4
kiwisolver                    1.4.5
MarkupSafe                    2.1.5
matplotlib                    3.8.4
numpy                         1.26.4
olefile                       0.47
packaging                     24.0
pillow                        10.3.0
pluggy                        1.4.0
Pygments                      2.18.0
pyparsing                     3.1.2
pyproject_hooks               1.0.0
pytest                        8.1.1
python-dateutil               2.9.0.post0
requests                      2.31.0
setuptools                    69.4.0
snowballstemmer               2.2.0
Sphinx                        7.3.7
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
tokenize_rt                   5.2.0
tomli                         2.0.1
urllib3                       2.2.1
wheel                         0.43.0
zipp                          3.18.2
```

**Comment by QuLogic** [comment]
Your numpy is broken; I don't know why you think this is something we can fix.
